export const products = [
  {
    id: 'almonds-500g',
    name: 'California Almonds 500g',
    subtitle: 'Premium quality',
    category: 'Dry Fruits',
    price: 1,
    stock: 48,
    available: true,
    accent: '#D79B52',
    emoji: '🥜',
  },
  {
    id: 'organic-honey-500ml',
    name: 'Organic Honey 500ml',
    subtitle: '100% natural',
    category: 'Grocery',
    price: 1,
    stock: 26,
    available: true,
    accent: '#F1A01F',
    emoji: '🍯',
  },
  {
    id: 'green-tea-25',
    name: 'Green Tea 25 Bags',
    subtitle: 'Antioxidant rich',
    category: 'Beverages',
    price: 1,
    stock: 62,
    available: true,
    accent: '#2C8A54',
    emoji: '🍵',
  },
  {
    id: 'terracotta-planter',
    name: 'Terracotta Planter',
    subtitle: 'Handmade medium pot',
    category: 'Home & Garden',
    price: 1,
    stock: 15,
    available: true,
    accent: '#B96939',
    emoji: '🪴',
  },
  {
    id: 'lavender-candle',
    name: 'Lavender Candle',
    subtitle: 'Hand poured',
    category: 'Home & Decor',
    price: 1,
    stock: 34,
    available: true,
    accent: '#8E6CC7',
    emoji: '🕯️',
  },
]
