export const products = [
  {
    id: 'almonds-500g',
    name: 'California Almonds 500g',
    subtitle: 'Premium quality',
    category: 'Dry Fruits',
    price: 1,
    stock: 48,
    available: true,
    accent: '#D79B52',
    emoji: '🥜',
  },
  {
    id: 'organic-honey-500ml',
    name: 'Organic Honey 500ml',
    subtitle: '100% natural',
    category: 'Grocery',
    price: 1,
    stock: 26,
    available: true,
    accent: '#F1A01F',
    emoji: '🍯',
  },
  {
    id: 'green-tea-25',
    name: 'Green Tea 25 Bags',
    subtitle: 'Antioxidant rich',
    category: 'Beverages',
    price: 1,
    stock: 62,
    available: true,
    accent: '#2C8A54',
    emoji: '🍵',
  },
  {
    id: 'terracotta-planter',
    name: 'Terracotta Planter',
    subtitle: 'Handmade medium pot',
    category: 'Home & Garden',
    price: 1,
    stock: 15,
    available: true,
    accent: '#B96939',
    emoji: '🪴',
  },
  {
    id: 'lavender-candle',
    name: 'Lavender Candle',
    subtitle: 'Hand poured',
    category: 'Home & Decor',
    price: 1,
    stock: 34,
    available: true,
    accent: '#8E6CC7',
    emoji: '🕯️',
  },
]

export const recentQuestions = [
  {
    id: 'q-1',
    customer: 'Neha Sharma',
    time: '11:32 AM',
    question: 'What is available in your store?',
    status: 'Replied by AI',
  },
  {
    id: 'q-2',
    customer: 'Rohan Verma',
    time: '10:58 AM',
    question: 'Do you deliver to JP Nagar?',
    status: 'Replied by AI',
  },
  {
    id: 'q-3',
    customer: 'Priya Nair',
    time: '10:21 AM',
    question: 'Is the Organic Honey pure?',
    status: 'Replied by AI',
  },
  {
    id: 'q-4',
    customer: 'Amit Patel',
    time: 'Yesterday',
    question: 'Can I get a bulk discount on 10 pcs?',
    status: 'Missed',
  },
]
