export const products = [
  {
    id: 'sage-satin-midi-dress',
    name: 'Sage Satin Midi Dress',
    subtitle: 'Adjustable straps · Sizes 8–16',
    category: 'Dresses',
    price: 1,
    stock: 12,
    available: true,
    accent: '#7A8B61',
    emoji: '👗',
  },
  {
    id: 'onyx-ribbed-co-ord-set',
    name: 'Onyx Ribbed Co-ord Set',
    subtitle: 'Crop top + wide-leg trousers · Sizes 8–14',
    category: 'Sets',
    price: 1,
    stock: 9,
    available: true,
    accent: '#242424',
    emoji: '🖤',
  },
  {
    id: 'mocha-wide-leg-trousers',
    name: 'Mocha Wide-Leg Trousers',
    subtitle: 'High waist · Sizes 8–16',
    category: 'Bottoms',
    price: 1,
    stock: 14,
    available: true,
    accent: '#8B6F5A',
    emoji: '👖',
  },
  {
    id: 'cloud-oversized-linen-shirt',
    name: 'Cloud Oversized Linen Shirt',
    subtitle: 'Relaxed fit · Sizes S–XL',
    category: 'Tops',
    price: 1,
    stock: 17,
    available: true,
    accent: '#E9E5DD',
    emoji: '🤍',
  },
  {
    id: 'sand-structured-blazer',
    name: 'Sand Structured Blazer',
    subtitle: 'Single-breasted · Sizes 8–16',
    category: 'Outerwear',
    price: 1,
    stock: 8,
    available: true,
    accent: '#C2A98D',
    emoji: '🧥',
  },
  {
    id: 'noir-ruched-mini-dress',
    name: 'Noir Ruched Mini Dress',
    subtitle: 'Stretch fit · Sizes 8–14',
    category: 'Dresses',
    price: 1,
    stock: 11,
    available: true,
    accent: '#191919',
    emoji: '👗',
  },
  {
    id: 'ivory-pleated-maxi-skirt',
    name: 'Ivory Pleated Maxi Skirt',
    subtitle: 'Flowing silhouette · Sizes 8–16',
    category: 'Bottoms',
    price: 1,
    stock: 13,
    available: true,
    accent: '#DED8CB',
    emoji: '🤍',
  },
  {
    id: 'classic-straight-leg-jeans',
    name: 'Classic Straight-Leg Jeans',
    subtitle: 'Mid-blue denim · Sizes 26–34',
    category: 'Bottoms',
    price: 1,
    stock: 18,
    available: true,
    accent: '#58789A',
    emoji: '👖',
  },
  {
    id: 'slate-mini-shoulder-bag',
    name: 'Slate Mini Shoulder Bag',
    subtitle: 'Structured crossbody · One size',
    category: 'Accessories',
    price: 1,
    stock: 10,
    available: true,
    accent: '#9B95A0',
    emoji: '👜',
  },
  {
    id: 'pearl-block-heel-sandals',
    name: 'Pearl Block-Heel Sandals',
    subtitle: '8 cm heel · Sizes 36–42',
    category: 'Shoes',
    price: 1,
    stock: 15,
    available: true,
    accent: '#E8E2D9',
    emoji: '👠',
  },
]
